version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    executor:
      name: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: npm run frontend:install
      - run: npm run frontend:build
      - run: npm run frontend:deploy
  backend:
    executor:
      name: node/default
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run: npm run backend:install
      - run: npm run backend:build
      - run: npm run backend:test
      - run: npm run backend:deploy
workflows:
  deploy:
    jobs:
      - frontend
      - backend
