version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    executor:
      name: node/default
    steps:
      - node/install
      - checkout
      - run: npm run frontend:install
      - run: npm run frontend:build
      - aws-cli/setup
      - run: npm run frontend:deploy
  backend:
    executor:
      name: node/default
    steps:
      - node/install
      - checkout
      - run: npm run backend:install
      - run: npm run backend:build
      - run: npm run backend:test
      - aws-cli/setup
      - eb/setup
workflows:
  deploy:
    jobs:
      - frontend
      - backend
      - eb/deploy:
          context: aws-creds
          app-dir: storefront-api/
          environment-name: storefront-api-dev
          requires:
            - backend
