version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  frontend:
    executor:
      name: node/default
      tag: '18'
    steps:
      - checkout
      - run: npm run frontend:install
      - run: npm run frontend:build
      - run: npm run frontend:deploy
  backend:
    executor:
      name: node/default
      tag: '18'
    steps:
      - checkout
      - run: npm run backend:install
      - run: npm run backend:build
      - run: npm run backend:test
      - run: npm run backend:deploy
workflows:
  deploy:
    jobs:
      - frontend
      - backend
