version: '3'
services:
  storefront_api:
    command:
      - postgres
    container_name: postgres
    entrypoint:
      - docker-entrypoint.sh
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=full_stack_user
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin
      - GOSU_VERSION=1.14
      - LANG=en_US.utf8
      - PG_MAJOR=14
      - PG_VERSION=14.2-1.pgdg110+1
      - PGDATA=/var/lib/postgresql/data
    hostname: 20b49dbb9ab4
    image: postgres
    ipc: private
    logging:
      driver: json-file
      options: {}
    ports:
      - 5432:5432/tcp
networks: {}
